config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#settings'
  devise_for :admins

  resources :admins do
    resources :products do
      collection { post :import }
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  validates :username,
            :presence => true,
            :uniqueness => {
              :case_sensitive => false
            } # etc.

  has_many :products

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :admin_id, :price, presence: true

  # default_scope -> { order(name: :asc) }

  belongs_to :admin, dependent: :destroy

  def self.search(query, user)
    # where(:name => query)
    q = query.capitalize
    user.products.where("name like ?",  "%#{q}%")
  end

  def self.import(file, user)
    if file && user
      CSV.foreach(file.path, headers: true) do |row|

        product_hash = row.to_hash
        product = user.products.where(id: product_hash["id"])

        if product.count == 1
          product.first.update_attributes(product_hash)
        else
          user.products.create!(product_hash)
        end # end if !product.nil?
      end # end CSV.foreach
      return true
    else
      return false
    end
  end # end self.import(file)
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |a| a.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |a| a.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |a| a.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!

  before_action :set_admin
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  def index
    if params[:search]
      @products = @admin.products.search(params[:search], @admin).order('created_at DESC').paginate(:page => params[:page], :per_page => 25)
    else
      @products = @admin.products.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 25)
    end
  end

  def import
    if Product.import(params[:file], @admin)
      redirect_to root_url, notice: "Products imported."
    else
      flash[:notice] = "Oops something went wrong with the download"
      redirect_to settings_path
    end
  end

  def show
  end

  def new
    @product = @admin.products.build
  end

  def create
    @product = @admin.products.build(product_params)
    if @product.save
      redirect_to admin_products_path(@admin)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @product.update_attributes(product_params)
      redirect_to admin_products_path(current_admin)
    else
      render :edit
    end
  end

  def destroy
    @product.delete

    redirect_to admin_products_path(current_admin)
  end

  private

    def set_admin
      @admin = current_admin
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:admin_id, :name, :size, :quantity, :price, :description, :sort)
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def settings

  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def total_cost(products)
    total = 0
    products.each do |prod|
      total += (prod.price * prod.quantity)
    end
    return total
  end

  def search_index(search_word)
    @products = Product.where(name: "#{search_word}")
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

  def any_information(product)
    info = product.description ? product.description : 'No product information, to add click on the product name and edit the description'
    return info
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    <% if current_admin %>
        <%= link_to "Log-Out", destroy_admin_session_path, method: :delete, class: "btn navbar-brand"  %>
        <p class="navbar-brand">Welcome <%= current_admin.username.capitalize %></p>
      <% else %>
        <%= link_to "Log-In", new_admin_session_path, class: "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <% if current_admin %>
        <%= form_tag(admin_products_path(current_admin), method: :get, class: "navbar-form navbar-left", id: "search-form") do %>
          <div class="form-group input-append">
            <%= text_field_tag :search, params[:search], class: "form-control span2", placeholder: "Search Products" %>
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        <% end %>
      <% end %>



      <ul class="nav navbar-nav navbar-right">
      <% if current_admin %>
        <li><%= link_to 'Home Page', admin_products_path(current_admin), class: "navbar-brand" %></li>
      <% end %>
        <li><%= link_to 'Settings', root_path, class: "navbar-brand" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bungalow Bliss</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar"%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
  <div class="form"><%= bootstrap_form_for [@admin, @product] do |p| %>

    <%= p.text_field :name, autofocus: true %>

    <%= p.text_field :price, prepend: "$" %>
    <div class="row">
      <div class="col-md-6">
        <%= p.text_field :size %>
      </div>
      <div class="col-md-6">
        <%= p.text_field :quantity %>
      </div>
    </div>
    <%= p.text_area :description %>

    <%= p.submit class: "btn btn-info"%>

    <%= link_to '<- Back', root_path, class: "btn btn-default" %>
    <% end %>
  </div>

app/views/products/edit.html.erb
<h1 class="text-center">Edit product</h1>
<div class="col-md-3"></div>
<div class="col-md-6">
  <%= render "products/form" %>
</div>
<div class="col-md-3"></div>

app/views/products/index.html.erb
<h1><%=link_to 'Products', admin_products_path(@admin) %></h1>
<%= link_to 'Add Product', new_admin_product_path(current_admin), class: "btn btn-success" %>
<hr>
<h2>Grand Total: <%= number_to_currency(total_cost(current_admin.products)) %></h2>

<div class="table-responsive">
  <table class="pretty" border="1">
  <th scope="col" class="text-center totip" width="100px" data-toggle="tooltip" data-placement="top" title="Click to sort A-Z click again to sort Z-A"><%= sortable "name" %></th>
  <th scope="col" class="text-center" width="100px">Size</th>
  <th scope="col" class="text-center totip" width="100px" data-toggle="tooltip" data-placement="top" title="Click to sort Price High to Low and Low to High"><%= sortable "price" %></th>
  <th scope="col" class="text-center" width="100px">Quantity</th>
  <% @products.each do |p| %>
    <tr>
      <td scope="row">
      <span tabindex="0" class="glyphicon glyphicon-question-sign" data-toggle="popover" data-trigger="focus" data-placement="bottom" title="<%= p.name %> Information" data-content="<%= any_information(p) %>"></span>
        <%= link_to p.name, admin_product_path(current_admin, p)%>
      </td scope="row">
      <td class="size text-center">
        <%= p.size %>
      </td>
      <td class="price text-center">
        <%= number_to_currency(p.price) %>
      </td>
      <td class="qty text-center">
        <%= p.quantity %>
      </td>
    </tr>
  <% end %>

  </table>
</div>
<h2> Page Total: <%= number_to_currency(total_cost(@products)) %></h2>
<div class="text-center">
  <%= will_paginate @products %>
</div>
<br>

app/views/products/new.html.erb
<h1 class="text-center">Add a new product</h1>
<div class="col-md-3"></div>
<div class="col-md-6">
  <%= render "products/form" %>
</div>
<div class="col-md-3"></div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<h2>Price: <%= number_to_currency(@product.price) %></h2>
<h2>QTY: <%= @product.quantity %></h2>
<h2>Size: <%= @product.size %></h2>
<h2>Description: <%= @product.description %></h2>
<%= link_to 'Back', admin_products_path(@admin), class: "btn btn-default" %>
<%= link_to 'Edit', edit_admin_product_path(@admin, @product), class: "btn btn-default" %>
<%= link_to 'Delete', admin_product_path(@admin, @product), class: "btn btn-default", method: :delete, data: {:confirm => "Are you sure you want to delete #{@product.name}"}%>

app/views/static_pages/settings.html.erb
<div class="row">
<%= link_to 'Back', root_path, class: "btn btn-default"  %>
   <a class="btn btn-info" href="mailto:evjay.a@gmail.com" target="_blank">Email Evan <span class="glyphicon glyphicon-send"></span></a>
</div>
<h1>Settings</h1>
<hr>

<%if current_admin %>
<div>
  <h5>Import Products</h3>
  <%= form_tag import_admin_products_path(current_admin), multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import", class: "btn btn-success btn-sm" %>
  <% end %>
</div>
<% end %>
<br>